# Generated by Django 3.0.4 on 2020-03-29 14:58

import apps.ioffer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('accounts', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOffer',
            fields=[
                ('countrycode', models.CharField(choices=[('CH', 'Schweiz'), ('DE', 'Deutschland'), ('AT', 'Österreich')], default='CH', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_first', models.CharField(default='', max_length=50)),
                ('name_last', models.CharField(default='', max_length=50)),
                ('plz', models.CharField(max_length=5, null=True)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('umkreis', models.IntegerField(choices=[(1, '<10 km'), (2, '<20 km'), (3, '<40 km'), (4, '>40 km')], null=True)),
                ('availability_start', models.DateField(default=django.utils.timezone.now, null=True)),
                ('braucht_bezahlung', models.IntegerField(choices=[(2, 'Ich freue mich über eine Vergütung, helfe aber auch ohne'), (1, 'Ich benötige eine Vergütung')], default=2)),
                ('zeitliche_verfuegbarkeit', models.IntegerField(choices=[(1, '10h pro Woche'), (2, '20h pro Woche'), (3, '30h pro Woche'), (4, '40h pro Woche')], null=True)),
                ('datenschutz_zugestimmt', models.BooleanField(default=False, validators=[apps.ioffer.models.validate_checkbox])),
                ('einwilligung_datenweitergabe', models.BooleanField(default=False, validators=[apps.ioffer.models.validate_checkbox])),
                ('sonstige_qualifikationen', models.CharField(blank=True, default='keine', max_length=200)),
                ('unterkunft_gewuenscht', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.ZipCode')),
                ('offer_functions', models.ManyToManyField(to='role.Function')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
            ],
            options={
                'ordering': ['plz'],
            },
        ),
    ]
