# Generated by Django 3.0.4 on 2020-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioffer',
            name='name_first',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='name_last',
            field=models.CharField(default='', max_length=50),
        ),
    ]
