# Generated by Django 3.0.4 on 2020-03-29 10:47

import apps.ioffer.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ioffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioffer',
            name='availability_start',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='braucht_bezahlung',
            field=models.IntegerField(choices=[(2, 'Ich freue mich über eine Vergütung, helfe aber auch ohne'), (1, 'Ich benötige eine Vergütung')], default=2),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='countrycode',
            field=models.CharField(choices=[('CH', 'Schweiz'), ('DE', 'Deutschland'), ('AT', 'Österreich')], default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='datenschutz_zugestimmt',
            field=models.BooleanField(default=False, validators=[apps.ioffer.models.validate_checkbox]),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='einwilligung_datenweitergabe',
            field=models.BooleanField(default=False, validators=[apps.ioffer.models.validate_checkbox]),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='sonstige_qualifikationen',
            field=models.CharField(blank=True, default='keine', max_length=200),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='umkreis',
            field=models.IntegerField(choices=[(1, '<10 km'), (2, '<20 km'), (3, '<40 km'), (4, '>40 km')], null=True),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='unterkunft_gewuenscht',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='ioffer',
            name='zeitliche_verfuegbarkeit',
            field=models.IntegerField(choices=[(1, '10h pro Woche'), (2, '20h pro Woche'), (3, '30h pro Woche'), (4, '40h pro Woche')], null=True),
        ),
    ]
