# Generated by Django 3.0.4 on 2020-03-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ioffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioffer',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ioffer.Role'),
        ),
    ]
