# Generated by Django 3.0.4 on 2020-03-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioffer', '0002_ioffer_location'),
        ('ioffer', '0002_auto_20200329_1047'),
    ]

    operations = [
    ]
