version: '3.7'

services:

  backend:
    volumes:
      - './backend:/curaSWISS-backend'
    ports:
      - '80:8000'
    networks:
      - network
    env_file:
      - backend.prod.env
      - database.prod.env
    environment:
     - DJANGO_SETTINGS_MODULE=curaSWISS.settings.production
    command: gunicorn -c /curaSWISS-backend/gunicorn.conf.py curaSWISS.wsgi

  database:
    image: postgres
    volumes:
     - ./database/data:/var/lib/postgresql/data
     - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
     - ./database/postgresql.conf:/etc/postgresql.conf
    restart: always
    env_file:
     - database.prod.env
    expose:
     -  5432
    networks:
     - network
    command: postgres -c config_file=/etc/postgresql.conf

networks:
 network:
