version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 8000
    volumes:
      - './backend:/curaSWISS-backend'
    ports:
      - '8000:8000'

