# Generated by Django 3.0.4 on 2020-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MEDICAL', 'Medicine'), ('SHOPPING', 'Shopping')], default='MEDICAL', max_length=50, unique=True)),
                ('functions', models.ManyToManyField(related_name='functions', to='role.Function')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
