# Generated by Django 3.0.4 on 2020-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='short_text',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='short_text',
            field=models.CharField(default='', max_length=20),
        ),
    ]
