# Generated by Django 3.0.4 on 2020-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20200329_1412'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='valid_roles',
        ),
        migrations.AddField(
            model_name='skill',
            name='valid_function',
            field=models.ManyToManyField(to='role.Function'),
        ),
    ]
