# Generated by Django 3.0.4 on 2020-03-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20200329_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='bla',
        ),
    ]
