# Generated by Django 3.0.4 on 2020-03-29 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INeed',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization_name', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('other_information', models.TextField(default='')),
                ('responsible_person', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('appears_in_map', models.BooleanField(default=True)),
                ('countrycode', models.CharField(choices=[('CH', 'Schweiz')], default='CH', max_length=2)),
                ('needed_functions', models.ManyToManyField(to='role.Function')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role')),
            ],
            options={
                'ordering': ['zip_code'],
            },
        ),
    ]
