# Generated by Django 3.0.4 on 2020-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20200329_1412'),
        ('ineed', '0002_ineed_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ineed',
            name='needed_skills',
            field=models.ManyToManyField(to='skill.Skill'),
        ),
    ]
