# Generated by Django 3.0.4 on 2020-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ineed', '0005_auto_20200329_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ineed',
            name='countrycode',
        ),
    ]
